### ISSUE TITLE
Cover image not created from RST source

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookconverter#2]
Sample:  https://www.gutenberg.org/ebooks/1399

1/3/9/1399/1399-rst/images/cover.jpg is correctly inserted into the EPUB and MOBI "with images" files. 

However, the cover formats are not created in cache/epub/1399, i.e. pg1399.cover.small.jpg and pg1399.cover.medium.jpg. And therefore, there is no cover image to display for the landing page. These supplemental files should be generated.

**Comment by eshellman** [comment]
This is fixed
