### ISSUE TITLE
Notification requests from production team

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookconverter#32]
For the backend notification code (Notifier.py), please consider this request: "Is it possible to have the name of the book and a link to the landing page. For me, that would make these success messages useful and meaningful."

**Comment by eshellman** [comment]
I looked at doing adding the book name, but it would require code restructuring. adding a link to the landing page is easy, and we should be able to do that in a bugfix release.

**Comment by asylumcs** [comment]
Thanks. I'll set the expectations with the whitewashers about the link but not the title.

**Comment by eshellman** [comment]
closing because successes are no longer notified #33 #34
